# Autogenerated wrapper script for dtcmp_jll for aarch64-linux-gnu-mpi+openmpi
export libdtcmp

using CompilerSupportLibraries_jll
using lwgrp_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("dtcmp")
JLLWrappers.@declare_library_product(libdtcmp, "libdtcmp.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, lwgrp_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libdtcmp,
        "lib/libdtcmp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
